[development]
SQLALCHEMY_DATABASE_URI = 'SEU_BANCO_DE_DESENVOLVIMENTO'
SECRET_KEY = "SUA_SECRET_KEY"


[production]
SQLALCHEMY_DATABASE_URI = 'SEU_BANCO_DE_PRODUCAO'
SENTRY_DSN = 'SEU_DSN_SENTRY'
SECRET_KEY = "SUA_SECRET_KEY"